### ISSUE TITLE
sticky action used during finetuning?

### ISSUE THREAD

**Issue by kevinghst** [mila-iqia/SGI#3]
Hi!

Quick question - did you use sticky actions during finetuning?

The paper doesn't say. Also, by looking at your code, it seems that the sticky action is disabled: 
https://github.com/mila-iqia/SGI/blob/master/src/rlpyt_atari_env.py#L75

Thanks for your clarification,
Kevin

**Comment by MaxASchwarzer** [comment]
No, we didn't use sticky actions at all, since prior work on Atari100k afaict never has.  I don't have any data on how enabling them affects results.  We can add a note clarifying that to the paper.
